{
 "title": "PostgreSQL",
 "tags": [
  "db",
  "PostgreSQL"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus_source", "label": "Source Prometheus", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   },
   {
    "name": "datname",
    "label": "BDD",
    "query": {
     "query": "label_values(pg_database_size_bytes{datname!~\"template[0-9]+\", instance=\"$instance\", job=\"$job\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Etat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connexions actives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "nb_connexion"
    },
    {
     "expr": "pg_settings_max_connections{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "nb_connexion_max"
    }
   ]
  },
  {
   "title": "Taille BDD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fichier fds",
   "type": "stat",
   "description": "Fichiers processus",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COMMIT/min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples fetched",
   "type": "stat",
   "description": "Pourcentage de tuples lus depuis l'index par rapport au nombre total de tuples mis en jeux - Sur 10s",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{job=\"$job\", instance=\"$instance\"}[15s]) / rate(pg_stat_database_tup_returned{job=\"$job\", instance=\"$instance\"}[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Démarré le",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Démarré depuis",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre BDD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fichier temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{job=\"$job\", instance=\"$instance\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROLLBACK/min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_rollback{job=\"$job\", instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block hit",
   "type": "stat",
   "description": "Taux de bloc lus depuis le buffer (hit) par rapport aux blocs lus directement (read)",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{job=\"$job\", instance=\"$instance\"}[15s])/(rate(pg_stat_database_blks_hit{job=\"$job\", instance=\"$instance\"}[15s])+rate(pg_stat_database_blks_read{job=\"$job\", instance=\"$instance\"}[15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation RAM",
   "type": "timeseries",
   "description": "Mémoire RAM consommée en octet moyennée sur 5 min",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}[30s])",
     "legendFormat": "RAM"
    },
    {
     "expr": "rate(process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}[30s])",
     "legendFormat": "Totale"
    }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "timeseries",
   "description": "Temps CPU consommé en octet moyenné sur 30 secondes",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[30s])*1000",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "File descriptor",
   "type": "timeseries",
   "description": "Nombre de fichiers ouverts par processus",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Nombre de fichiers"
    }
   ]
  },
  {
   "title": "Mémoire buffer allouée",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_buffers_alloc_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "pg_stat_bgwriter_buffers_backend_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Backend"
    },
    {
     "expr": "pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Backend fsync"
    },
    {
     "expr": "pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "pg_stat_bgwriter_buffers_clean_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Clean"
    }
   ]
  },
  {
   "title": "Nombre de connexions",
   "type": "timeseries",
   "description": "Nombre de connexions simultanées",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "sum by(datname) (pg_stat_activity_count{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "pg_settings_max_connections{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Nb connexion max"
    }
   ]
  },
  {
   "title": "Taille",
   "type": "piechart",
   "description": "Espace disque occupé par les différentes BDD",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "datname"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "pg_locks_count{job=\"$job\", instance=\"$instance\"} != 0",
     "legendFormat": "{{datname}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Deadlock",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "pg_stat_database_deadlocks{job=\"$job\", instance=\"$instance\"} ",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{job=\"$job\", instance=\"$instance\"} [10s])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Paramètres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max connexion",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Checkpoint timeout",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_checkpoint_timeout_seconds{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Super user reserved connexions",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_superuser_reserved_connections{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Min WAL Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_min_wal_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Checkpoint completion target",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_checkpoint_completion_target{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "BDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Session actives",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(datname) (pg_stat_activity_count{job=\"$job\", instance=\"$instance\", datname=~\"$datname\", state=\"active\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Taux de requêtes sur 10s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{job=\"$job\", instance=\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "COMMIT"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{job=\"$job\", instance=\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "ROLLBACK"
    }
   ]
  },
  {
   "title": "Opérations",
   "type": "timeseries",
   "description": "Taux d'opérations sur 10s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{job=\"$job\", instance=~\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "SELECT"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{job=\"$job\", instance=~\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "INSERT"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{job=\"$job\", instance=~\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{job=\"$job\", instance=~\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Tuple morts",
   "type": "table",
   "description": "Tables ayant le plus grand nombre de tuples morts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{job=\"$job\", instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_stat_user_tables_n_live_tup{job=\"$job\", instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "Comparaison du nombre de lignes récupérées via index (fetched) par rapport aux nombre total de lignes utilisées (returned) sur 10s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{job=\"$job\", instance=\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "Tuples fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{job=\"$job\", instance=\"$instance\", datname=~\"$datname\"}[10s])",
     "legendFormat": "Tuples returned"
    }
   ]
  },
  {
   "title": "Block IO",
   "type": "timeseries",
   "description": "Taux sur 10s de blocs lus directement (read) par rapport aux blocs lu depuis le buffer (hit).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit{job=\"$job\", instance=\"$instance\", datname=~\"$datname\"}[10s]))",
     "legendFormat": "Block hit"
    },
    {
     "expr": "sum(rate(pg_stat_database_blks_read{job=\"$job\", instance=\"$instance\", datname=~\"$datname\"}[10s]))",
     "legendFormat": "Block read"
    }
   ]
  }
 ]
}