# /etc/alertmanager/alertmanager.yml

# 
#                                                        ^                            ^
#                                                        │                            │
#                                                    notification                notification 
#                                                        <─────── repeat_interval ────>
#                          <─────── group_interval ─────>
#   <────group_wait ──────>  
#   ^         ^          ^                                                                                ^
#   │         │          │                                       If alert resolves                        │
# Event 1   Event 2    Event 3                                         │                                resolve
#                                                                      v                             notification
#                                                                      <───────── resolve_timeout ────────>
#

global:
  # Configure your SMTP server info  
  smtp_auth_username:     '{{ proxmox_smtp_username }}'
  smtp_auth_password:     '{{ proxmox_smtp_password }}'
  smtp_auth_identity:     '{{ proxmox_smtp_username }}'
  smtp_from:              '{{ proxmox_smtp_from_address }}'
  smtp_smarthost:         '{{ proxmox_smtp_server }}:{{ proxmox_smtp_port }}'
  smtp_require_tls:       false

  # AlertManager wait prevents excessive alert noise when a condition fluctuates around the threshold
  resolve_timeout:        1m

route:
  group_by:               ['alertname', 'instance']

  # Wait for a short time to collect similar alerts before sending the first notification.
  group_wait:             30s

  # After sending the first notification for a group,
  #  wait this long before sending the next notification for new alerts in the same group.
  group_interval:         1m

  # Notifications continue every x time if the alert remains unresolved.
  repeat_interval:        1d

  receiver:              'email-alerts'
  routes:
    - receiver:          'buzzer'
    
receivers:
- name: 'email-alerts'
  email_configs:
  - to: '{{ alertmanager_mail_to }}'
    send_resolved: true
- name: 'buzzer'
  webhook_configs:
  - url: 'http://{{ proxmox_host_ip }}:9000/alert'

#inhibit_rules:
#- source_match:
#    severity: 'critical'
#  target_match:
#    severity: 'warning'
#  equal: ['alertname', 'instance']
