# ------------------------------------------------------------------------------------------
#    name: proxmox.backup.yaml
#
# ------------------------------------------------------------------------------------------
playbooks:

        #********************************************************************************************************
        - name:                                       'Backup'
          host:                                       'proxmox'          
        # ______________________________________________________________________________________________________            
        # playbook                  
          tasks:  
            # ==================================================================================================
            # ssh 
            # ==================================================================================================
            - name:                                   'proxmox_ssh_open_with_private_key'
              ignore_errors:                          'no'

            # ==================================================================================================
            # Backup
            # ==================================================================================================              
            - name:                                   'proxmox_backup'
              ignore_errors:                          'no'
              vars:
                proxmox_vm_ids:                       [184]                                     # 181,182,183,184,185
                proxmox_archive:                      '{{ proxmox_datastore_backup }}'          # archive for the backup
                proxmox_backup_mode:                  'snapshot'                                # snapshot | stop | suspend
                proxmox_backup_compress:              'zstd'                                    # zstd | gzip | lzo | none
                proxmox_backup_exclude_path:          ''                                        # exclude path for the backup
        # ______________________________________________________________________________________________________    
        - name:                                       'exit'
        # ______________________________________________________________________________________________________
