# ------------------------------------------------------------------------------------------
#    name: proxmox.firewall.install.yaml
#
# ------------------------------------------------------------------------------------------
playbooks:

        #********************************************************************************************************
        - name:                                       'Firewall install'
          host:                                       'proxmox'          
        # ______________________________________________________________________________________________________            
        # playbook                  
          tasks:  
            # ==================================================================================================
            # ssh 
            # ==================================================================================================
            - name:                                   'proxmox_ssh_open_with_private_key'
              ignore_errors:                          'no'

            # ==================================================================================================
            # Setup proxmox firewall 
            # ==================================================================================================
            
            # ___________________________________________________________________________________________________
            # Prometheus  (listens on 9090)
            - name: 'proxmox_firewall'
              ignore_errors: 'no'
              container_id: '{{ prometheus_container_id }}'
              vars:
                firewall_options:
                  firewall:      'Yes'
                  dhcp:          'No'
                  ndp:           'Yes'
                  radv:          'No'
                  macfilter:     'Yes'
                  ipfilter:      'No'
                  log_level_in:  'nolog'
                  log_level_out: 'nolog'
                  policy_in:     'DROP'
                  policy_out:    'ACCEPT'
                firewall_rules:
                  - 'IN ACCEPT -source 0.0.0.0/0 -p tcp -dport 9090 -log nolog  # prometheus'

            # ___________________________________________________________________________________________________
            # Alertmanager (listens on 9093)
            - name: 'proxmox_firewall'
              ignore_errors: 'no'
              container_id: '{{ alertmanager_container_id }}'
              vars:
                firewall_options:
                  firewall:      'Yes'
                  dhcp:          'No'
                  ndp:           'Yes'
                  radv:          'No'
                  macfilter:     'Yes'
                  ipfilter:      'No'
                  log_level_in:  'nolog'
                  log_level_out: 'nolog'
                  policy_in:     'DROP'
                  policy_out:    'ACCEPT'
                firewall_rules:
                  - 'IN ACCEPT -source 0.0.0.0/0 -p tcp -dport 9093 -log nolog  # alertmanager'

            # ___________________________________________________________________________________________________
            # Grafana (listens on 3000)
            - name: 'proxmox_firewall'
              ignore_errors: 'no'
              container_id: '{{ grafana_container_id }}'
              vars:
                firewall_options:
                  firewall:      'Yes'
                  dhcp:          'No'
                  ndp:           'Yes'
                  radv:          'No'
                  macfilter:     'Yes'
                  ipfilter:      'No'
                  log_level_in:  'nolog'
                  log_level_out: 'nolog'
                  policy_in:     'DROP'
                  policy_out:    'ACCEPT'
                firewall_rules:
                  - 'IN ACCEPT -source 0.0.0.0/0 -p tcp -dport 3000 -log nolog  # grafana'

            # ___________________________________________________________________________________________________
            # Nginx container (for port 80, or 443, etc.)
            - name: 'proxmox_firewall'
              ignore_errors: 'no'
              container_id: '{{ nginx_node01_container_id }}'
              vars:
                firewall_options:
                  firewall:      'Yes'
                  dhcp:          'No'
                  ndp:           'Yes'
                  radv:          'No'
                  macfilter:     'Yes'
                  ipfilter:      'No'
                  log_level_in:  'nolog'
                  log_level_out: 'nolog'
                  policy_in:     'DROP'
                  policy_out:    'ACCEPT'
                firewall_rules:
                  - 'IN ACCEPT -source 0.0.0.0/0 -p tcp -dport 80 -log nolog   # http'
                # - 'IN ACCEPT -source 0.0.0.0/0 -p tcp -dport 443 -log nolog # https' (if needed)

            # ___________________________________________________________________________________________________
            # PostgreSQL container (listening on 5432)
            - name: 'proxmox_firewall'
              ignore_errors: 'no'
              container_id: '{{ pgsql_node01_container_id }}'
              vars:
                firewall_options:
                  firewall:      'Yes'
                  dhcp:          'No'
                  ndp:           'Yes'
                  radv:          'No'
                  macfilter:     'Yes'
                  ipfilter:      'No'
                  log_level_in:  'nolog'
                  log_level_out: 'nolog'
                  policy_in:     'DROP'
                  policy_out:    'ACCEPT'
                firewall_rules:
                  - 'IN ACCEPT -source 0.0.0.0/0 -p tcp -dport 5432 -log nolog  # postgresql'           
        # ______________________________________________________________________________________________________    
        - name:                                       'exit'
        # ______________________________________________________________________________________________________

