# ------------------------------------------------------------------------------------------
#    name: proxmox.pgsql.install.yaml
#
# ------------------------------------------------------------------------------------------
playbooks:

        #********************************************************************************************************
        - name:                                       'Postgresql install'
          host:                                       'proxmox'          
        # ______________________________________________________________________________________________________            
        # playbook                  
          tasks:  
            # ==================================================================================================
            # ssh 
            # ==================================================================================================
            - name:                                   'proxmox_ssh_open_with_private_key'
              ignore_errors:                          'no'
              
            #=====================================================================================================
            # Postgresql PRIMARY NODE SETUP (node01)
            #=====================================================================================================
            # create CT
            - name:                                   'proxmox_create_lxc'
              ignore_errors:                          'no'
              container_id:                           '{{ pgsql_node01_container_id }}'             # (integer) Unique VM ID
              vars:
                # Basic VM Information                
                hostname:                            '{{ pgsql_node01_name }}'                      # (string) Name of the host
                password:                            '{{ proxmox_password }}'
                # Memory Settings
                memory:                              4096                                            # (integer) RAM in MB
                numa_enabled:                        false                                           # (boolean) Whether NUMA is enabled
                swap:                                1024                                            # (integer) Swap in MB
                # CPU Settings  
                cores:                               8                                               # (integer) Number of Cores
                # OS Type & Other Options
                os:
                  ostype:                            'debian'                                        # (string) OS type
                  numafabric:                        false                                           # (boolean)
                  protection:                        false                                           # (boolean)
                  ostemplate:                        'local:vztmpl/{{ proxmox_download_lxc_image_name }}.{{ proxmox_download_lxc_file_ext }}'
                # Network Settings
                network:
                  name:                              'eth0'                                          # (string) Interface name
                  bridge:                            'vmbr0'                                         # (string) Bridge interface
                  firewall:                          false                                           # (boolean) Enable/disable firewall
                  tag:                               ~                                               # (null) VLAN tag
                  ip:                                '{{ pgsql_node01_ip }}/24'                      # (string) Static IP
                  gateway:                           '{{ gateway_lan }}'                             # (string) Gateway                    
                # Storage Settings
                storage:
                  rootfs:
                    storage:                         'local'                                         # (string) Storage name  
                    size:                            '35'                                            # (string) in gigabytes do not add G
                # Advanced Settings
                advanced:
                  onboot:                            true                                            # (boolean) Start VM on boot
                  startup:
                    order:                           1                                               # (integer) Startup order
                    up_delay:                        10                                              # (integer) Delay before starting
                    down_delay:                      0                                               # (integer) Delay before shutting down
                  # Critical for Grafana
                  features:
                    nesting:                         1                                               # (boolean) Allow nested containers
                    keyctl:                          1                                               # (boolean) Enable kernel keyring
                # Custom LXC config lines (like lxc.cap.drop:)  
                lxc_custom_lines:
                      - "unprivileged: 0"
                      - "lxc.apparmor.profile = unconfined"
                      - "lxc.cap.drop ="
                      - "lxc.cgroup2.devices.allow = c 10:200 rwm"
                      - "lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file"                  
            # ___________________________________________________________________________________________________
            # commands
            - name:                                   'proxmox_commands'
              ignore_errors:                          'no'        
              commands:              
               - 'pct start {{ pgsql_node01_container_id }}' 
            # ___________________________________________________________________________________________________
            # fix timezone for container
            - name:                                   'proxmox_fix_timezone_lxc'
              ignore_errors:                          'no'
              container_id:                           '{{ nginx_node01_container_id }}'                   
            # ___________________________________________________________________________________________________
            # install locale on lxc container
            - name:                                   'proxmox_local_install_lxc'
              ignore_errors:                          'no'
              container_id:                           '{{ pgsql_node01_container_id }}'
            # ___________________________________________________________________________________________________
            # security create .pgpass
            - name:                                   'proxmox_merge_files_lxc'
              ignore_errors:                          'no'
              container_id:                           '{{ pgsql_node01_container_id }}'  
              vars:
                merge_files:                 
                  - name:                             'repmgr.pgpass' 
                    local_file:                       '{{ base_directory }}/config/repmgr/repmgr.pgpass'
                    remote_file:                      '/tmp/repmgr.pgpass'
                    remote_merge_file:                '/var/lib/postgresql/.pgpass'
                    set_chmod:                        "0600"
                    set_chown:                        "{{  pgsql_super_user }}:{{  pgsql_super_user }}"
                  - name:                             'pgsql.pgpass' 
                    local_file:                       '{{ base_directory }}/config/pgsql/pgsql.pgpass'
                    remote_file:                      '/tmp/pgsql.pgpass'
                    remote_merge_file:                '/var/lib/postgresql/.pgpass'
                    set_chmod:                        "0600"
                    set_chown:                        "{{  pgsql_super_user }}:{{  pgsql_super_user }}" 
            # ___________________________________________________________________________________________________
            # install postgresql 
            - name:                                   'proxmox_pgsql_install_lxc'
              ignore_errors:                          'no'
              container_id:                           '{{ pgsql_node01_container_id }}'   
              vars: 
                package_to_install:                   'postgresql-server'
                sql_files:                 
                - name:                               'test.sql'
                  local_path:                         '{{ base_directory }}/config/pgsql/test.sql'
                  remote_path:                        '/tmp/test.sql'                
                  remote_path:                        '/tmp/test.sql'
            # ___________________________________________________________________________________________________
            # install postgres-exporter
            - name:                                   'proxmox_pgsql_exporter_install_lxc'
              ignore_errors:                          'no'
              container_id:                           '{{ pgsql_node01_container_id }}'
            
        # ______________________________________________________________________________________________________    
        - name:                                       'exit'
        # ______________________________________________________________________________________________________

