# ------------------------------------------------------------------------------------------
#    name: proxmox.test.yaml
#
# ------------------------------------------------------------------------------------------
playbooks:

        #********************************************************************************************************
        - name:                                       'Manage Proxmox Containers'
          host:                                       'proxmox'          
        # ______________________________________________________________________________________________________            
        # playbook                  
          tasks:  
             # ==================================================================================================
            # ssh 
            # ==================================================================================================
            - name:                                   'proxmox_ssh_open_with_private_key'
              ignore_errors:                          'no'
              
            # ___________________________________________________________________________________________________
            # Restore
            - name:                                   'proxmox_restore'
              ignore_errors:                          'no'
              vars:
                proxmox_restore_files:
                - 'vzdump-lxc-184-2025_05_20-01_54_44.tar.zst'
                proxmox_archive:                      '{{ proxmox_datastore_backup }}'
                proxmox_restore_storage:              'local'
                proxmox_restore_force:                true
        # ______________________________________________________________________________________________________    
        - name:                                       'exit'
        # ______________________________________________________________________________________________________

                